version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USERNAME : NAME
      POSTGRES_DB : TEST_DB
    ports:
      - 5432:5432